return function ()
    Vector2 = require("Shared.Types.Vector2")
    Vector3 = require("Shared.Types.Vector3")
    Pivot2D = require("Shared.Types.Pivot2D")
    Transform2D = require("Shared.Types.Transform2D")
    Color = require("Shared.Types.Color")
    Rect = require("Shared.Types.Rect")
    Transform3D = require("Shared.Types.Transform3D")
    Object = require("Shared.Types.ClassicObject")
    Enum = require("Shared.Types.Enum")
    Path = require("Shared.Types.Path")
    IdentifierType = require("Shared.Types.Identifier")
    GradientSequence = require("Shared.Types.GradientSequence")
    Effect = require("Shared.Types.Effects")
    --ipairs = require("Shared.Types.ipairs")
end