return function ()
    Pivot2D = require("Shared.Types.Pivot2D")
    Transform2D = require("Shared.Types.Transform2D")
    Enum = require("Shared.Types.Enum")
    Color = require("Shared.Types.Color")
    Rect = require("Shared.Types.Rect")
    Transform3D = require("Shared.Types.Transform3D")
    Vector2 = require("Shared.Types.Vector2")
    Vector3 = require("Shared.Types.Vector3")
    Object = require("Shared.Types.ClassicObject")
end